### ISSUE TITLE
Container entrypoint shouldn't be /bin/sh

### ISSUE THREAD

**Issue by chgl** [samply/blaze#1034]
In https://github.com/samply/blaze/pull/1014, the container was changed to run blaze as a sub-process of /bin/sh.

This isn't ideal since /bin/sh doesn't forward signals to its child processes by default, see https://petermalmgren.com/signal-handling-docker/ https://hynek.me/articles/docker-signals/ . Any graceful shutdown handling - if present - will most likely not be invoked.

As an aside, I can still recommend using a base image that doesn't include a shell in the first place to slightly improve the security posture - I remember doing https://github.com/samply/blaze/pull/153 a few years ago but I see it has been reverted.

**Comment by alexanderkiel** [comment]
We use `/bin/sh` because we have to set `LD_PRELOAD` depending on the runtime architecture. So we need a shell to call `arch`. Also we use `exec` to get rid of the shell for exactly your point about the signals.

We moved from Google Distroless AdoptOpenJDK in #401 because Distroless was no longer maintained. We now use Eclipse Temurin which is recommended by [RedHat](https://developers.redhat.com/articles/2022/09/16/updating-docker-hubs-openjdk-image).

I'll leave that issue open in case you have a good idea to get jemalloc loaded without using a shell. Thanks for bringing this up.

**Comment by chgl** [comment]
Ah, sorry for the noise I didn't even see the `exec`. You can avoid using a shell/environment expansion by specifying the library name without any slashes, ie:

```Dockerfile
ENV LD_PRELOAD=libjemalloc.so.2
CMD ["java", "-jar",  "blaze-0.21.0-standalone.jar"]
```

See https://man7.org/linux/man-pages/man8/ld.so.8.html for the search path used. There's also a set of pre-defined build arguments when using buildkit: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope. Unfortunately, as far as I can tell none of them expand to `x86_64` but are normalize to `amd64`.

I believe distroless is still being maintained, the last build was 2 days ago. But if I remember correctly, the images were renamed at some point and support for Java 8 was dropped - which was the reason it was removed as the default from Jib. Of course, it's just a preference in the end with some minor benefits to security.

**Comment by alexanderkiel** [comment]
Thanks for mentioning that I can load shared object files without specifying the absolute path if they can be found in standard directories. I didn't think about that possibility. I also tried to use the build args but as you mentioned the platforms doesn't match the paths.

However I'll stick to the temurin image as long as there is no strong evidence for real enhanced security because for what I know it's just the most widely used Java image today.

**Comment by chgl** [comment]
Sure! IMO, the biggest advantage security-wise is that the lack of a shell and utils like curl, wget, etc. thwarts naive attempts for threat-persistence and lateral movement. The downside being that it's more difficult to debug at runtime (unless using ephemeral containers). But theres definitely nothing wrong with the temurin image.

**Comment by alexanderkiel** [comment]
Sadly curl is even needed for Docker health checks some people use.

**Comment by chgl** [comment]
Gotcha, not a problem of course. Don't get me started on the Docker-specific implementation of healthchecks which I don't think is a great design decision - and luckily not part of the OCI spec. If you're interested, I could create a PR at some point to provide distroless support as a dedicated image layer - similiar to how I did in https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/217/files which now pushes the image as a default distroless "flavor" and a tomcat one:
<img width="243" alt="image" src="https://github.com/samply/blaze/assets/5307555/5ce7d8da-847c-4f69-8eff-751487b33f8f">

Thanks again for adressing the concern!
