### ISSUE TITLE
Add SSL/TLS option

### ISSUE THREAD

**Issue by drewverlee** [samply/blaze#117]
## Problem: 

We want our users to communicate end to end using the HTTPS protocol which means we need the traffic to be SSL/TLS encrypted. Currently, Blaze doesn't support this, as the ssl-context needed is an option passed to alpha when the server starts. 

## Potential Solution: 

Make passing a ssl-context to alpha configurable. Mostly likely as a module so it's outside the server/system code.

**Comment by alexanderkiel** [comment]
In my opinion, it would be a better solution to put something like Nginx, Haproxy or Envoy in front of Blaze. Building Authentication into Blaze was already a tough call for me, but I can see the advantage to have direct access to token claims.

In a proaction deployment, I would always put a reverse proxy in front of Blaze. Running Blaze in it's own VM or inside a Kubernetes pod, it's possible to bind the HTTP port of Blaze to localhost, so that the only possible outside access path has to go through the proxy. 

Such proxies have far more stable, better configurable and possibly more performant TLS implementations.

What do you think? Would it be possible in your deployment scenario to use a reverse proxy?
