### ISSUE TITLE
Fix Returning Resources with Non-Matching Identifier

### ISSUE THREAD

**Issue by alexanderkiel** [samply/blaze#2111]
FHIR searches for identifiers like `[base]/Patient?identifier=foo` can sometimes return non-matching results even in case there is no Patient with the identifier `foo` at all. However in every case all matching results are returned.

A related issue is #1685. Which only solved the problem in the case that the resource with the matching identifier existed and a second, non-matching resource was returned.

The reason is that the index structure of Blaze uses hashing and hash collisions are not resolved. The issue #2028 will resolve that root cause.

**Comment by jorieck** [comment]
Hello, I recently stumbled upon a problem that I believe is the same as described here.

In some cases I have found that when searching for resources with `identifier=<system>|<value>`, one resource with a completetly different `Identifier.value` is returned. I noticed this in our ETL-processes: a "Conditional Create" request and an enabled referential integrity check lead to rejecting some Bundles with a `Referential integrity violated. Resource 'Observation/...' doesn't exist.`-OperationOutcome (my suspicion: a wrong Observation "has been found", so the Observation sent in the Bundle is not created due to Conditional Create, but a DiagnosticReport in the same Bundle requires that Observation for references, hence the error).

In every case, the resource with the given identifier does not exist in the Blaze at that time. This issue occurs only when the system is specified in the identifier search parameter:  `identifier=<system>|<value>`.  Just searching for `identifier=<value>` returns the correct result (should be '0'). The `<system>`-substring is rather long (71 characters). After POST-ing the resource with said identifier normally, the Blaze returns the correct result for the same search request, even with the system included.

Maybe the long system name causes a hash collision.

**Comment by alexanderkiel** [comment]
Hi @jorieck, your discoveries are right. it's a hash collision problem. I already have a branch of blaze with indices not using hashing at all. I only have to find the time to really integrate this in Blaze. Also finding a way to migrate to that new index schema is not done yet. Try to use only the value.
