### ISSUE TITLE
Missing "total" field for bundle pagination in CQL requests with Blaze 0.28

### ISSUE THREAD

**Issue by djuarezgf** [samply/blaze#2185]
**_Description_**: In previous versions of Blaze, executing a CQL query that returned a large response (requiring pagination across multiple bundles) included a "total" field within each bundle. This field provided the total number of bundles, allowing us to calculate the estimated remaining time for the process interacting with Blaze.

However, in version 0.28, this "total" information is no longer included in the bundle response. This change significantly impacts our ability to gauge progress and manage resources effectively.

**_Blaze Version_**: **0.28** (previous versions included the "total" field as expected)

**_Query (FHIR-Search)_**: **/Patient**

According to the FHIR specification, the "Bundle" resource should contain a "total" field indicating the total count of matching resources (see [FHIR Bundle Documentation](https://hl7.org/fhir/bundle.html)). Could you clarify whether this is an intentional change or an issue in the latest release?

The "total" field is essential for our processes, and we would greatly appreciate any guidance on restoring this functionality or alternative solutions.

**Comment by alexanderkiel** [comment]
Hi David, your problem is about a FHIR Search query you do after you executed the CQL Query via `$evaluate-measure` to receive the Patients - right? Do you use the `_list` search param like I have documented [here](https://github.com/samply/blaze/blob/main/docs/cql-queries/api.md#list-search-parameter)? 

On Blaze v0.28 the following FHIR Search query with a List resource containing only 1 patient works:

```sh
curl -s 'http://localhost:8080/fhir/Patient?_list=DEZLRKBIRZDQJC73' | jq .total
1
```

Is that your scenario? Or do you use a different FHIR Search query?

**Comment by djuarezgf** [comment]
Oh, yes, you are right. I have tested again. When I send a fhir search like /Patient, I get the "total" in the bundle. But when I use a CQL query and get the _list, then, I don't get the "total" in the bundle.

**Comment by alexanderkiel** [comment]
Do you have the exact FHIR Search query which doesn't;t return a total value?

**Comment by djuarezgf** [comment]
Yes, it would be `/Patient?_list=...` . In the exporter this happen here: https://github.com/samply/exporter/blob/29b304ba333c79d3ab230b316f095160eb75368e/src/main/java/de/samply/fhir/cql/CqlToFhirSearchConverter.java#L36

**Comment by djuarezgf** [comment]
genau

**Comment by alexanderkiel** [comment]
Do you have to use paging? E.g. are there more results as will fit on the first page?

**Comment by djuarezgf** [comment]
This is the FHIR search query I send to the HAPI FHIR client. I also provide the _revinclude parameters, which the HAPI FHIR client library appends to construct the final URL. Essentially, we're requesting Blaze to return a significant amount of related information for each patient.

We are using pagination and can successfully read all the pages provided by Blaze. However, the issue arises because the "total" number of pages is missing in the response bundle. Without this, we cannot calculate or display the progress of the operation.

**Comment by alexanderkiel** [comment]
Unfortunately, Blaze will not output a total value if the search contains at least one search parameter and the results will not fit on the first page. The reason is that I had to calculate the whole search result before seeing able to output the page only to calculate the total value. As I don't like to spend that time, I simply skipped outputting the total value. If you really need it, you can append `_summary=count` to the query which will force Blaze to calculate the total value but doesn't return the actual data. You could however issue two queries, first with `_summary=count` and then without.

In FHIR there is the special search parameter [_total](http://hl7.org/fhir/R4/search.html#total). I could implement it. With that, you could force the calculation of total also on your normal query. If you think that `_total` parameter would be useful for you, please open an issue. Thanks,

**Comment by djuarezgf** [comment]
In our case, I believe it would make more sense to include the _total search parameter. I’ll go ahead and create an issue for this.
