### ISSUE TITLE
Match BASE_URL to SERVER_PORT if it is not set explicitly

### ISSUE THREAD

**Issue by alexanderkiel** [samply/blaze#330]

**Comment by NamUKF** [comment]
SETUP:

blaze v0.16 |  ghcr.io/medizininformatik-initiative/blaze:0.16
nginx (reverse proxy) | nginxinc/nginx-unprivileged:1.20-alpine

-----
Problem:

Port Number gets lost, when querying for bundles.

![blaze](https://user-images.githubusercontent.com/111059110/188644773-201ec128-7cd7-41a3-8fc7-62bff8ec42bd.png)

The blaze FHIR Server, which is included in the feasibility Deploy (blaze,v0.16) (https://github.com/medizininformatik-initiative/feasibility-deploy/tree/main/feasibility-triangle) doesn't correctly set the port when paging through the bundles. 

Therefore some automation scripts, which use the "next link" and run into errors due to the potential bug. 

I am not 100% sure, whether this is the fault of the blaze FHIR Server or not, But wanted to ask for some second opinion. 
I have a similar setup with an Apache + blaze server (same version), which also is a simple reverse proxy, where the port isn't lost when querying to it.
However this might be a nginx + blaze fhir server specific issue, which is the reason for this ticket. 

------

Is there a variable which i have to set differently, so the baseurl + Port is set in the blaze fhir server ? Because the BASE_URL variable doesn't seem to have an impact on the provided links.

**Comment by alexanderkiel** [comment]
You can use the HTTP headers X-Forwarded-Host, X-Forwarded-Proto and Forwarded besides setting `BASE_URL`. I've documented that [here](https://github.com/samply/blaze/blob/c479410a9198526453a0df769ab7db2e6d5dd654/docs/api.md#absolute-urls).

**Comment by NamUKF** [comment]
Super thanks a lot for clarifying that ! :) I overread that. Setting the appropriately fixed the issue thanks !

**Comment by alexanderkiel** [comment]
Sounds good. So I will close this issue.
