### ISSUE TITLE
document development process

### ISSUE THREAD

**Issue by drewverlee** [samply/blaze#68]
greetings again
This concerns the development branch. Which i understand is a WIP :)

**problem**

I'm not sure how to use the existing development namespace. Specifically, when I start my repl in the project root using clojure-cli and so grabbing the root level deps, i'm not able to EVAL even the namespace form for blaze.dev. The specific error is that its missing the clojure tools namespace on the classpath. 

This makes me concerned that either my process is wrong. But its possible the project is just in transition. In the interim i had setup my own dev namespace in src/blaze/dev that used [integrant repl](https://github.com/weavejester/integrant-repl). 

But this namespace now too doesn't work as the blaze.edn file isn't a purely a integrant config file and the reader (previously i just used the integrant config reader) no longer works. The reader on development is a private function.

The combination of changes has me confused about how to proceed in terms of setting up a development process where i can launch the system and test things out that will stay compatible with the direction your going. 

**Solution**

setup and document a working development namespace.

Thanks again Alex.

**Comment by alexanderkiel** [comment]
> The specific error is that its missing the clojure tools namespace on the classpath.

You have to start the REPL with the `test` alias: `clj -A:test`

> But this namespace now too doesn't work as the blaze.edn file isn't a purely a integrant config file and the reader (previously i just used the integrant config reader) no longer works. The reader on development is a private function.

The `blaze.edn` file is no longer a pure integrant config map because I introduced feature toggles which can be added to `blaze.edn` under the `:features` key. The map under `:base-config` is also no longer a integrant config map because I use special `blaze` tagged literals. The goal is to build a layer over integrant in order to not depend on it at a public level. All the `blaze.edn` processing takes place in `blaze.system`.

The current state of the modularization is intermediate and non-public. The reason for this is that I had to find a way to move on with features we need in our project. We still can talk about the modularization and I'm thankful for every input, but I like to give it some time before making it really public.

Currently `blaze.edn` is read from the class path because I can't relay on a external `blaze.edn` because some sites don't use Docker but use `java -jar` instead.

I plan to resolve `blaze.edn` in multiple steps: build-in classpath, current working dir and configurable dir.

## My current development approach

### Whole System in REPL

* start a REPL with alias `test` and class path at the root of blaze
* go into `blaze.dev`
* evaluate `(init)`
* change something
* evaluate `(reset)`

### One Module in REPL from Cursive

* start a REPL with alias `test` and class path of the module using Cursive
* evaluate stuff
* run tests with Cursive

### Run all Tests

* on cmdline: `make test`

### Run one Module Test

* on cmdline: `make test-rest-api`
