### ISSUE TITLE
Fix _lastUpdated Search Returning a Resource more than Once

### ISSUE THREAD

**Issue by Mandalka** [samply/blaze#882]
I have some problems with the FHIR search parameter _lastUpdated

From my previous point of view not (yet?) plausible (see the last example) count examples from a Blaze server with some test resources:

/fhir/Observation?_summary=count

94065

/fhir/Observation?_lastUpdated=ge2023-01-11&_summary=count

43638

/fhir/Observation?_lastUpdated=lt2023-01-11&_summary=count

164377

Maybe the resource histories (i ingested/updated many resources multiple times mostly without changes in the data) of the resources are searched, too (is this a bug or a feature in this search parameter context?) since a "less than" search by

/fhir/Observation?_lastUpdated=lt2023-01-11

returns results which were updated later like for example:

"meta":{"lastUpdated":"2023-01-17T19:10:14.212Z"

(but most propably updated (multiple times) before 2023-01-11)

Maybe related to
https://github.com/samply/blaze/issues/680#issuecomment-1098950816
https://github.com/samply/blaze/issues/343

**Comment by alexanderkiel** [comment]
@Mandalka Thanks for reporting. You where right, for every recent version in the history, the current version of that resource was returned. Recent version means all versions identical to the current version. That problem was specific to _lastUpdated because the timestamp doesn't contribute to content hash. Other date searches had not this problem.

**Comment by alexanderkiel** [comment]
@Mandalka I've released [v0.19.2](https://github.com/samply/blaze/releases/tag/v0.19.2).
